### ISSUE TITLE
Are there plans to develop an admin pro ?

### ISSUE THREAD

**Issue by yayxs** [element-plus/rfcs#1]
First of all, a big thank you to the `element` (hereafter referred to as ele) team for their contributions to the community! We know that in the `vue2 era`, many enterprises use `ele` as the first framework in the middle and back office. What's more, use vue-element-admin directly. Dare to ask if the official team in the `vue3 era` has plans to release an enterprise-level `Pro version`. Someday Use element-plus like a Pro! For example, call an `element-plus-pro`.

---
首先非常感谢`element` （下文简称ele）团队为社区作出的贡献！我们知道在`vue2时代`，很多企业的中后台采用`ele` 作为首先框架。更甚者直接使用[vue-element-ui](https://github.com/PanJiaChen/vue-element-admin) 。斗胆问一下，在`vue3时代` 官方团队是否有计划出一个企业级`Pro版本`。是否有一天Use [element-plus](https://github.com/element-plus) like a Pro! 比如叫一个 `element-plus-pro`。

**Comment by JeremyWuuuuu** [comment]
Thank you for your support! As for now, we are barely have the resource to develop Element Plus, as for the `Pro` or `Admin` you mentioned, in a short period of time I don't think that we can do that, but I believe that there are already some projects out there based on Element Plus. The goal is that we can have feedbacks from those projects and help them to be better.  @xiaoxian521 I believe that he has started a project which could be something you want. ;) Thank you again for your support, we will keep working to make Element Plus better ;)

**Comment by yayxs** [comment]
> 谢谢您的支持！就目前而言，我们几乎没有资源开发Element Plus，至于`Pro`或者`Admin`你提到的，在很短的时间内我不认为我们可以做到，但我相信已经有一些项目在那里基于元素加。目标是我们可以从这些项目中获得反馈并帮助他们变得更好。 @xiaoxian521我相信他已经开始了一个可能是你想要的项目。;) 再次感谢您的支持，我们将继续努力使 Element Plus 变得更好；)
